# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build & Deploy

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    uses: LouisBrunner/.github/.github/workflows/lint-bun.yml@main
    permissions:
      contents: read
    with:
      run: |
        bun run all

  build-deploy:
    name: Build & Deploy
    needs: [test]
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: LouisBrunner/.github/.github/workflows/build-bun-pages.yml@main
    with:
      run: |
        bun i
        bun run build:examples
        cp -r dist/. .
        rm -rf dist
      path: _site
      jekyll: true
