name: Lint

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  configs:
    uses: LouisBrunner/.github/.github/workflows/lint-configs.yml@main
    permissions: {}
